---
title: "Main Notebook for the `{{cookiecutter.project_name}}` Project"
author: "{{cookiecutter.author_name}}"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
    pdf_document:
        latex_engine: xelatex
        number_sections: yes
        df_print: kable
        fig_caption: yes
        fig_width: 7
        fig_height: 7
        includes:
            in_header: "header.tex"
urlcolor: blue
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

show_setup <- FALSE
show_functions <- FALSE
show_figure_code <- FALSE
show_file_writes <- FALSE
show_code <- TRUE
```

# Environment

```{r, echo = !show_setup}
# To see the environment-setup code, recompile with `show_setup = TRUE`
```

```{r, echo = show_setup}
library(here)
```

```{r, echo = show_setup}
pkgs <- c()

for (pkg in pkgs) {
  suppressPackageStartupMessages(
    library(pkg, character.only = TRUE)
  )
}
```

```{r, echo = show_setup}
# For storing intermediate results that will be used in the text
sketches <- list()

# For storing results that will be presented in the Executive Summary
gallery <- list()
```

# Functions

```{r, echo = !show_functions}
# To see the function definitions, recompile with `show_functions = TRUE`
```

# Directories

---

<!-- Main text (imports / analysis etc) goes here -->

---

# Executive Summary

---

# Appendix

---
